package com.xworkz.ipl.boot;

import java.time.LocalDateTime;

import com.xworkz.ipl.dto.IplDto;
import com.xworkz.ipl.repository.IplRepository;
import com.xworkz.ipl.repository.IplRepositoryImpl;

public class IplRunner {

	public static void main(String[] args) {
		
		IplRepository repository=new IplRepositoryImpl();
		IplDto dto=new IplDto();
		dto.setCaptainName("DuPlesis");
		dto.setCreatedBy("malya");
		dto.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 10));
		dto.setDefeates(113);
		dto.setOwnerAlive(true);
		dto.setPurse(85);
		dto.setTeamName("rcb");
		dto.setUpdatedBy("bcci");
		dto.setUpdatedDate(LocalDateTime.now());
		dto.setWins(107);
		repository.create(dto);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto1=new IplDto();
		dto1.setCaptainName("dhoni");
		dto1.setCreatedBy("srinivas");
		dto1.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto1.setDefeates(86);
		dto1.setOwnerAlive(true);
		dto1.setPurse(100);
		dto1.setTeamName("csk");
		dto1.setUpdatedBy("rpsg");
		dto1.setUpdatedDate(LocalDateTime.now());
		dto1.setWins(121);
		repository.create(dto1);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto2=new IplDto();
		dto2.setCaptainName("rohit");
		dto2.setCreatedBy("nita");
		dto2.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 30));
		dto2.setDefeates(97);
		dto2.setOwnerAlive(true);
		dto2.setPurse(95);
		dto2.setTeamName("mi");
		dto2.setUpdatedBy("sachin");
		dto2.setUpdatedDate(LocalDateTime.now());
		dto2.setWins(129);
		repository.create(dto2);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto3=new IplDto();
		dto3.setCaptainName("rahul");
		dto3.setCreatedBy("avinash");
		dto3.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto3.setDefeates(6);
		dto3.setOwnerAlive(true);
		dto3.setPurse(75);
		dto3.setTeamName("gt");
		dto3.setUpdatedBy("ktk");
		dto3.setUpdatedDate(LocalDateTime.now());
		dto3.setWins(4);
		repository.create(dto3);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto4=new IplDto();
		dto4.setCaptainName("pandya");
		dto4.setCreatedBy("prashant");
		dto4.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto4.setDefeates(8);
		dto4.setOwnerAlive(true);
		dto4.setPurse(65);
		dto4.setTeamName("lg");
		dto4.setUpdatedBy("gurath");
		dto4.setUpdatedDate(LocalDateTime.now());
		dto4.setWins(2);
		repository.create(dto4);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto5=new IplDto();
		dto5.setCaptainName("kane");
		dto5.setCreatedBy("jagadeesh");
		dto5.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto5.setDefeates(1);
		dto5.setOwnerAlive(true);
		dto5.setPurse(55);
		dto5.setTeamName("srh");
		dto5.setUpdatedBy("hyderabad");
		dto5.setUpdatedDate(LocalDateTime.now());
		dto5.setWins(9);
		repository.create(dto5);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto6=new IplDto();
		dto6.setCaptainName("dk");
		dto6.setCreatedBy("srk");
		dto6.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto6.setDefeates(2);
		dto6.setOwnerAlive(true);
		dto6.setPurse(45);
		dto6.setTeamName("kkr");
		dto6.setUpdatedBy("kolkat");
		dto6.setUpdatedDate(LocalDateTime.now());
		dto6.setWins(2);
		repository.create(dto6);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto7=new IplDto();
		dto7.setCaptainName("pant");
		dto7.setCreatedBy("muthoot");
		dto7.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto7.setDefeates(3);
		dto7.setOwnerAlive(true);
		dto7.setPurse(35);
		dto7.setTeamName("dc");
		dto7.setUpdatedBy("delhi");
		dto7.setUpdatedDate(LocalDateTime.now());
		dto7.setWins(3);
		repository.create(dto7);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto8=new IplDto();
		dto8.setCaptainName("mayank");
		dto8.setCreatedBy("zinta");
		dto8.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto8.setDefeates(4);
		dto8.setOwnerAlive(true);
		dto8.setPurse(25);
		dto8.setTeamName("pk");
		dto8.setUpdatedBy("punjab");
		dto8.setUpdatedDate(LocalDateTime.now());
		dto8.setWins(8);
		repository.create(dto8);
		System.out.println(repository.total());
		System.out.println(System.lineSeparator());
		IplDto dto9=new IplDto();
		dto9.setCaptainName("rahul");
		dto9.setCreatedBy("avinash");
		dto9.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto9.setDefeates(6);
		dto9.setOwnerAlive(true);
		dto9.setPurse(75);
		dto9.setTeamName("gt");
		dto9.setUpdatedBy("ktk");
		dto9.setUpdatedDate(LocalDateTime.now());
		dto9.setWins(4);
		repository.create(dto9);
		System.out.println(repository.total());
		System.out.println("\n");
		IplDto dto10=new IplDto();
		dto10.setCaptainName("sanju");
		dto10.setCreatedBy("shipla");
		dto10.setCreatedDate(LocalDateTime.of(2022, 12, 12, 6, 20));
		dto10.setDefeates(8);
		dto10.setOwnerAlive(true);
		dto10.setPurse(15);
		dto10.setTeamName("rr");
		dto10.setUpdatedBy("rajasthan");
		dto10.setUpdatedDate(LocalDateTime.now());
		dto10.setWins(0);
		repository.create(dto10);
		System.out.println(repository.total());
	}

}
